server:
  port: 8085

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kekovasudi@gmail.com
    password: dyjpfacumjmqrowr

    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          starttls:
            enable: true